mailjet:
    api:
        key: 48895e542caaf1ab83625d63e1f4d86a
        secret: 6f1f688b54534bd2a5c183f9fcdd3d28
management:
    security:
        enabled: true
security:
    jwt:
        expiration-time: 3600000
        secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
server:
    port: 9002
    servlet:
        context-path: /api/v1
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        password: root
        url: jdbc:mariadb://localhost:3306/plantes_api
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: true
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    security:
        user:
            name: user
            password: '#P@ssword122'
springdoc:
    api-docs:
        path: /api-docs
