management:
    security:
        enabled: true
security:
    jwt:
        expiration-time: 3600000
        secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
server:
    port: 9002
    servlet:
        context-path: /api/v1
spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        password: ${DATABASE_PASSWORD}
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: true
        properties:
            hibernate:
                format_sql: true
        show-sql: true
    security:
        user:
            name: user
            password: '#P@ssword122'
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${EMAIL_USERNAME}
        password: ${EMAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
springdoc:
    api-docs:
        path: /api-docs
